name: github-pages

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: deploy
        uses: actions/deploy-pages@v4
        with:
          token: ${{ github.token }}

